# Generated by Django 5.2.15 on 2026-09-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_device_name_alter_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_fallback',
        ),
        migrations.AddField(
            model_name='content',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='media_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.geofencezone'),
        ),
    ]
