# Generated by Django 5.2.15 on 2026-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_content_is_fallback_content_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='Display as highway/default ad when outside defined geofences.'),
        ),
        migrations.AddField(
            model_name='content',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
